-- ================================================================================
-- i2s_master : I2S (Inter-IC Sound) bus master controller
--
-- I2S is a 3-wire serial bus for connecting digital audio devices:
--   * SCK  (Serial Clock)       - bit clock, generated by master
--   * WS   (Word Select)        - L/R channel select, generated by master
--   * SD   (Serial Data)        - time-multiplexed L/R audio data
--
-- This master supports:
--   * Philips standard I2S framing (WS changes one SCK before MSB)
--   * Left-justified and right-justified modes (configurable)
--   * 16/24/32-bit word widths
--   * TX (playback) and RX (capture) directions
--   * Configurable sample rate via clock divider
--
-- Target: Altera Cyclone III EP3C16F484C6N.
-- ================================================================================
library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity i2s_master is
    generic (
        CLK_FREQ   : integer := 50000000;  -- system clock in Hz
        SAMPLE_RATE: integer := 48000;     -- audio sample rate in Hz
        WORD_WIDTH : integer := 24;        -- audio word width: 16, 24, or 32
        MODE       : string  := "philips"  -- "philips", "left_just", "right_just"
    );
    port (
        clk         : in  std_logic;
        reset       : in  std_logic;       -- active-high synchronous

        -- Control / status
        enable      : in  std_logic;       -- '1' = running, '0' = idle
        tx_start    : in  std_logic;       -- pulse to load TX word pair
        rx_start    : in  std_logic;       -- pulse to request RX word pair
        tx_l_data   : in  std_logic_vector(31 downto 0); -- left channel TX
        tx_r_data   : in  std_logic_vector(31 downto 0); -- right channel TX
        rx_l_data   : out std_logic_vector(31 downto 0); -- left channel RX
        rx_r_data   : out std_logic_vector(31 downto 0); -- right channel RX
        tx_ready    : out std_logic;       -- '1' = ready for next TX pair
        rx_ready    : out std_logic;       -- '1' = RX pair available
        busy        : out std_logic;       -- '1' = currently transferring

        -- I2S bus (master generates SCK and WS)
        i2s_sck     : out std_logic;       -- serial bit clock
        i2s_ws      : out std_logic;       -- word select (L/R)
        i2s_sd_tx   : out std_logic;       -- serial data output
        i2s_sd_rx   : in  std_logic        -- serial data input
    );
end entity i2s_master;

architecture rtl of i2s_master is

    -- Clock divider: SCK frequency = sample_rate * word_width * 2
    -- For 48kHz / 24-bit: SCK = 48000 * 24 * 2 = 2.304 MHz
    constant SCK_FREQ  : integer := SAMPLE_RATE * WORD_WIDTH * 2;
    constant DIV       : integer := CLK_FREQ / (SCK_FREQ * 2) - 1;  -- half-period

    type state_t is (S_IDLE, S_WAIT_WS, S_TX_L, S_TX_R, S_RX_L, S_RX_R, S_DONE);
    signal state : state_t := S_IDLE;

    signal sck_reg      : std_logic := '0';
    signal ws_reg       : std_logic := '0';  -- '0' = left, '1' = right (Philips)
    signal sd_tx_reg    : std_logic := '0';

    signal clk_cnt      : integer range 0 to DIV := 0;
    signal bit_cnt      : integer range 0 to WORD_WIDTH := 0;
    signal sck_toggle   : std_logic := '0';  -- track SCK edges

    signal tx_l_reg     : std_logic_vector(31 downto 0) := (others => '0');
    signal tx_r_reg     : std_logic_vector(31 downto 0) := (others => '0');
    signal rx_l_reg     : std_logic_vector(31 downto 0) := (others => '0');
    signal rx_r_reg     : std_logic_vector(31 downto 0) := (others => '0');

    signal tx_ready_reg : std_logic := '1';
    signal rx_ready_reg : std_logic := '0';
    signal busy_reg     : std_logic := '0';

    -- For Philips mode, WS changes one SCK before the first data bit
    -- For left-justified, WS changes simultaneously with the first data bit
    -- For right-justified, WS changes after the last data bit

begin

    i2s_sck   <= sck_reg;
    i2s_ws    <= ws_reg;
    i2s_sd_tx <= sd_tx_reg;
    tx_ready  <= tx_ready_reg;
    rx_ready  <= rx_ready_reg;
    busy      <= busy_reg;

    -- Master clock and data generation process
    i2s_proc : process(clk)
        variable half_period : boolean;
        variable bit_idx : integer range 0 to 31;
    begin
        if rising_edge(clk) then
            if reset = '1' then
                state        <= S_IDLE;
                sck_reg      <= '0';
                ws_reg       <= '0';
                sd_tx_reg    <= '0';
                clk_cnt      <= 0;
                bit_cnt      <= 0;
                tx_ready_reg <= '1';
                rx_ready_reg <= '0';
                busy_reg     <= '0';
                rx_l_data    <= (others => '0');
                rx_r_data    <= (others => '0');
            else
                case state is
                    when S_IDLE =>
                        sck_reg      <= '0';
                        ws_reg       <= '0';
                        sd_tx_reg    <= '0';
                        busy_reg     <= '0';
                        tx_ready_reg <= '1';
                        if enable = '1' and tx_start = '1' then
                            tx_l_reg     <= tx_l_data;
                            tx_r_reg     <= tx_r_data;
                            tx_ready_reg <= '0';
                            busy_reg     <= '1';
                            clk_cnt      <= 0;
                            bit_cnt      <= WORD_WIDTH;
                            -- Philips: WS goes low one SCK before first bit
                            ws_reg       <= '0';
                            state        <= S_WAIT_WS;
                        elsif enable = '1' and rx_start = '1' then
                            rx_ready_reg <= '0';
                            busy_reg     <= '1';
                            clk_cnt      <= 0;
                            bit_cnt      <= WORD_WIDTH;
                            ws_reg       <= '0';
                            state        <= S_RX_L;
                        end if;

                    when S_WAIT_WS =>
                        -- Wait one SCK half-period, then start left channel
                        if clk_cnt = DIV then
                            clk_cnt <= 0;
                            -- Toggle SCK
                            sck_reg <= not sck_reg;
                            -- On falling edge of SCK, prepare first bit
                            if sck_reg = '1' then
                                bit_idx := WORD_WIDTH - 1;
                                if MODE = "philips" or MODE = "left_just" then
                                    sd_tx_reg <= tx_l_reg(bit_idx);
                                end if;
                                state <= S_TX_L;
                                bit_cnt <= WORD_WIDTH - 1;
                            end if;
                        else
                            clk_cnt <= clk_cnt + 1;
                        end if;

                    when S_TX_L =>
                        -- Transmit left channel data
                        if clk_cnt = DIV then
                            clk_cnt <= 0;
                            sck_reg <= not sck_reg;
                            -- On falling edge, shift out next bit
                            if sck_reg = '1' then
                                if bit_cnt > 0 then
                                    bit_cnt <= bit_cnt - 1;
                                    bit_idx := bit_cnt - 1;
                                    sd_tx_reg <= tx_l_reg(bit_idx);
                                else
                                    -- Left channel done, switch to right
                                    ws_reg <= '1';  -- WS high for right channel
                                    bit_cnt <= WORD_WIDTH - 1;
                                    bit_idx := WORD_WIDTH - 1;
                                    sd_tx_reg <= tx_r_reg(bit_idx);
                                    state <= S_TX_R;
                                end if;
                            end if;
                        else
                            clk_cnt <= clk_cnt + 1;
                        end if;

                    when S_TX_R =>
                        -- Transmit right channel data
                        if clk_cnt = DIV then
                            clk_cnt <= 0;
                            sck_reg <= not sck_reg;
                            if sck_reg = '1' then
                                if bit_cnt > 0 then
                                    bit_cnt <= bit_cnt - 1;
                                    bit_idx := bit_cnt - 1;
                                    sd_tx_reg <= tx_r_reg(bit_idx);
                                else
                                    -- Right channel done
                                    sd_tx_reg    <= '0';
                                    tx_ready_reg <= '1';
                                    busy_reg     <= '0';
                                    ws_reg       <= '0';
                                    state        <= S_IDLE;
                                end if;
                            end if;
                        else
                            clk_cnt <= clk_cnt + 1;
                        end if;

                    when S_RX_L =>
                        -- Receive left channel data
                        if clk_cnt = DIV then
                            clk_cnt <= 0;
                            sck_reg <= not sck_reg;
                            -- On rising edge, sample input data
                            if sck_reg = '0' then
                                if bit_cnt > 0 then
                                    bit_cnt <= bit_cnt - 1;
                                    rx_l_reg(bit_cnt) <= i2s_sd_rx;
                                else
                                    rx_l_reg(0) <= i2s_sd_rx;
                                    ws_reg <= '1';  -- Switch to right
                                    bit_cnt <= WORD_WIDTH - 1;
                                    state <= S_RX_R;
                                end if;
                            end if;
                        else
                            clk_cnt <= clk_cnt + 1;
                        end if;

                    when S_RX_R =>
                        -- Receive right channel data
                        if clk_cnt = DIV then
                            clk_cnt <= 0;
                            sck_reg <= not sck_reg;
                            if sck_reg = '0' then
                                if bit_cnt > 0 then
                                    bit_cnt <= bit_cnt - 1;
                                    rx_r_reg(bit_cnt) <= i2s_sd_rx;
                                else
                                    rx_r_reg(0) <= i2s_sd_rx;
                                    rx_l_data    <= rx_l_reg;
                                    rx_r_data    <= rx_r_reg;
                                    rx_ready_reg <= '1';
                                    busy_reg     <= '0';
                                    ws_reg       <= '0';
                                    state        <= S_IDLE;
                                end if;
                            end if;
                        else
                            clk_cnt <= clk_cnt + 1;
                        end if;

                    when S_DONE =>
                        busy_reg     <= '0';
                        tx_ready_reg <= '1';
                        state        <= S_IDLE;

                    when others =>
                        state <= S_IDLE;
                end case;
            end if;
        end if;
    end process i2s_proc;

end architecture rtl;
